import type { Metadata } from "next";
import { Inter, Playfair_Display, Montserrat } from 'next/font/google';
import { Manrope, Figtree, IBM_Plex_Serif } from 'next/font/google'
import "./globals.css";
const manrope = Manrope({
  subsets: ['latin'],
  variable: '--font-manrope',
})

const figtree = Figtree({
  subsets: ['latin'],
  variable: '--font-figtree',
})

const plexSerif = IBM_Plex_Serif({
  weight: ['400', '600'],
  subsets: ['latin'],
  variable: '--font-plex-serif',
})


const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

const playfair = Playfair_Display({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-playfair',
});

const montserrat = Montserrat({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-montserrat',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       className={`${inter.variable} ${playfair.variable} ${montserrat.variable} ${manrope.variable} ${figtree.variable} ${plexSerif.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
